"""Add reshared_by_id to share tables

Revision ID: fa13d93ca641
Revises: d4f1b1614ce9
Create Date: 2025-09-15 11:16:16.190688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa13d93ca641'
down_revision = 'd4f1b1614ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_file_share', sa.Column('reshared_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_file_share', 'user', ['reshared_by_id'], ['id'])
    op.add_column('user_folder_share', sa.Column('reshared_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_folder_share', 'user', ['reshared_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_folder_share', type_='foreignkey')
    op.drop_column('user_folder_share', 'reshared_by_id')
    op.drop_constraint(None, 'user_file_share', type_='foreignkey')
    op.drop_column('user_file_share', 'reshared_by_id')
    # ### end Alembic commands ###
